[build-system]
requires = ["setuptools >= 65.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "U2"
version = "1.0.0"
description = "Android automation in python using uiautomator2"
authors = [{ name = "Lmoq", email = "foxwitch12@gmail.com" }]

